### PR TITLE
fix(reset.css): remove antialiased

### PR DESCRIPTION
**Pull request by gazdagergo**
Font rendering on CE was without `antialiased`, so I removed it from FEF.

### CODE REVIEW

**Comment by ruffle1986** [comment]
It's ok to have it there because we want antialiased fonts on the style guide's webpage (intellyo.design) as well.

**Comment by gazdagergo** [comment]
but this setting makes the font non-antialiased somehow (left is before, right is after the commit)
image

**Comment by ruffle1986** [comment]
We have agreed on not removing this css rule.

**Comment by gazdagergo** [comment]
👍

**Pull request closed without merging**
