### PR TITLE
chore: remove package lock from version control.

### PR DESCRIPTION
**Pull request by ruffle1986**

### CODE REVIEW

**Comment by ruffle1986** [comment]
Already added to npmrc in circle ci.

**Comment by ruffle1986** [comment]
@oroce @kristof0425 @gazdagergo please, somebody :)

**Comment by ruffle1986** [comment]
I'm planning to use it again in the future so I'd like to close this pull request without merging. Whatdythink? 

related pull request --> https://github.com/purposeindustries/content-editor/pull/1561

**Comment by oroce** [comment]
let's close this, but we need to find a proper way of handling this.

**Pull request closed without merging**
